package org.biblio.p7.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-19T22:10:30.034+01:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://service.p7.biblio.org/", name = "AuthentificationService")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthentificationService {

    @WebMethod
    @RequestWrapper(localName = "rechercherlesLecteurs", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherlesLecteurs")
    @ResponseWrapper(localName = "rechercherlesLecteursResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherlesLecteursResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Lecteur> rechercherlesLecteurs();

    @WebMethod
    @RequestWrapper(localName = "modifierLecteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierLecteur")
    @ResponseWrapper(localName = "modifierLecteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierLecteurResponse")
    public void modifierLecteur(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Lecteur arg0
    );

    @WebMethod
    @RequestWrapper(localName = "recherchercoordonnee", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.Recherchercoordonnee")
    @ResponseWrapper(localName = "recherchercoordonneeResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RecherchercoordonneeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.biblio.p7.service.Coordonnees recherchercoordonnee(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod
    @RequestWrapper(localName = "controlerLecteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ControlerLecteur")
    @ResponseWrapper(localName = "controlerLecteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ControlerLecteurResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.biblio.p7.service.Lecteur controlerLecteur(
        @WebParam(name = "identifiant", targetNamespace = "")
        java.lang.String identifiant,
        @WebParam(name = "motDepasse", targetNamespace = "")
        java.lang.String motDepasse
    );

    @WebMethod
    @RequestWrapper(localName = "coordonneesparlecteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.Coordonneesparlecteur")
    @ResponseWrapper(localName = "coordonneesparlecteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.CoordonneesparlecteurResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Coordonnees> coordonneesparlecteur(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "modifierCooronnees", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierCooronnees")
    @ResponseWrapper(localName = "modifierCooronneesResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierCooronneesResponse")
    public void modifierCooronnees(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Coordonnees arg0
    );

    @WebMethod
    @RequestWrapper(localName = "ajouterCoordonnees", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterCoordonnees")
    @ResponseWrapper(localName = "ajouterCoordonneesResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterCoordonneesResponse")
    public void ajouterCoordonnees(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Coordonnees arg0
    );

    @WebMethod
    @RequestWrapper(localName = "rechercher", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.Rechercher")
    @ResponseWrapper(localName = "rechercherResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.biblio.p7.service.Lecteur rechercher(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod
    @RequestWrapper(localName = "ajouterLecteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterLecteur")
    @ResponseWrapper(localName = "ajouterLecteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterLecteurResponse")
    public void ajouterLecteur(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Lecteur arg0
    );

    @WebMethod
    @RequestWrapper(localName = "supprimerLecteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerLecteur")
    @ResponseWrapper(localName = "supprimerLecteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerLecteurResponse")
    public void supprimerLecteur(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod
    @RequestWrapper(localName = "rechercherparNom", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherparNom")
    @ResponseWrapper(localName = "rechercherparNomResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherparNomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.biblio.p7.service.Lecteur rechercherparNom(
        @WebParam(name = "nom", targetNamespace = "")
        java.lang.String nom
    );
}
