
package org.biblio.p7.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-19T22:10:29.964+01:00
 * Generated source version: 3.2.5
 *
 */
public final class AuthentificationService_AuthentificationServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.p7.biblio.org/", "AuthentificationService");

    private AuthentificationService_AuthentificationServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AuthentificationService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AuthentificationService_Service ss = new AuthentificationService_Service(wsdlURL, SERVICE_NAME);
        AuthentificationService port = ss.getAuthentificationServicePort();

        {
        System.out.println("Invoking rechercherlesLecteurs...");
        java.util.List<org.biblio.p7.service.Lecteur> _rechercherlesLecteurs__return = port.rechercherlesLecteurs();
        System.out.println("rechercherlesLecteurs.result=" + _rechercherlesLecteurs__return);


        }
        {
        System.out.println("Invoking modifierLecteur...");
        org.biblio.p7.service.Lecteur _modifierLecteur_arg0 = null;
        port.modifierLecteur(_modifierLecteur_arg0);


        }
        {
        System.out.println("Invoking recherchercoordonnee...");
        java.lang.Integer _recherchercoordonnee_iD = null;
        org.biblio.p7.service.Coordonnees _recherchercoordonnee__return = port.recherchercoordonnee(_recherchercoordonnee_iD);
        System.out.println("recherchercoordonnee.result=" + _recherchercoordonnee__return);


        }
        {
        System.out.println("Invoking controlerLecteur...");
        java.lang.String _controlerLecteur_identifiant = "";
        java.lang.String _controlerLecteur_motDepasse = "";
        org.biblio.p7.service.Lecteur _controlerLecteur__return = port.controlerLecteur(_controlerLecteur_identifiant, _controlerLecteur_motDepasse);
        System.out.println("controlerLecteur.result=" + _controlerLecteur__return);


        }
        {
        System.out.println("Invoking coordonneesparlecteur...");
        java.lang.Integer _coordonneesparlecteur_arg0 = null;
        java.util.List<org.biblio.p7.service.Coordonnees> _coordonneesparlecteur__return = port.coordonneesparlecteur(_coordonneesparlecteur_arg0);
        System.out.println("coordonneesparlecteur.result=" + _coordonneesparlecteur__return);


        }
        {
        System.out.println("Invoking modifierCooronnees...");
        org.biblio.p7.service.Coordonnees _modifierCooronnees_arg0 = null;
        port.modifierCooronnees(_modifierCooronnees_arg0);


        }
        {
        System.out.println("Invoking ajouterCoordonnees...");
        org.biblio.p7.service.Coordonnees _ajouterCoordonnees_arg0 = null;
        port.ajouterCoordonnees(_ajouterCoordonnees_arg0);


        }
        {
        System.out.println("Invoking rechercher...");
        java.lang.Integer _rechercher_iD = null;
        org.biblio.p7.service.Lecteur _rechercher__return = port.rechercher(_rechercher_iD);
        System.out.println("rechercher.result=" + _rechercher__return);


        }
        {
        System.out.println("Invoking ajouterLecteur...");
        org.biblio.p7.service.Lecteur _ajouterLecteur_arg0 = null;
        port.ajouterLecteur(_ajouterLecteur_arg0);


        }
        {
        System.out.println("Invoking supprimerLecteur...");
        java.lang.Integer _supprimerLecteur_iD = null;
        port.supprimerLecteur(_supprimerLecteur_iD);


        }
        {
        System.out.println("Invoking rechercherparNom...");
        java.lang.String _rechercherparNom_nom = "";
        org.biblio.p7.service.Lecteur _rechercherparNom__return = port.rechercherparNom(_rechercherparNom_nom);
        System.out.println("rechercherparNom.result=" + _rechercherparNom__return);


        }

        System.exit(0);
    }

}
