package org.biblio.p7.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-19T22:10:30.049+01:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "AuthentificationService",
                  wsdlLocation = "file:/Users/aurelienmimouni/Downloads/projP7/P7ClientLibrairie/cli-webapp/target/resources/wsdl/AuthentificationService.wsdl",
                  targetNamespace = "http://service.p7.biblio.org/")
public class AuthentificationService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.p7.biblio.org/", "AuthentificationService");
    public final static QName AuthentificationServicePort = new QName("http://service.p7.biblio.org/", "AuthentificationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/aurelienmimouni/Downloads/projP7/P7ClientLibrairie/cli-webapp/target/resources/wsdl/AuthentificationService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthentificationService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/aurelienmimouni/Downloads/projP7/P7ClientLibrairie/cli-webapp/target/resources/wsdl/AuthentificationService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthentificationService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthentificationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthentificationService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AuthentificationService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthentificationService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthentificationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AuthentificationService
     */
    @WebEndpoint(name = "AuthentificationServicePort")
    public AuthentificationService getAuthentificationServicePort() {
        return super.getPort(AuthentificationServicePort, AuthentificationService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthentificationService
     */
    @WebEndpoint(name = "AuthentificationServicePort")
    public AuthentificationService getAuthentificationServicePort(WebServiceFeature... features) {
        return super.getPort(AuthentificationServicePort, AuthentificationService.class, features);
    }

}
