package org.biblio.p7.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-19T22:10:30.423+01:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://service.p7.biblio.org/", name = "OuvrageService")
@XmlSeeAlso({ObjectFactory.class})
public interface OuvrageService {

    @WebMethod
    @RequestWrapper(localName = "ajouterOuvrage", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterOuvrage")
    @ResponseWrapper(localName = "ajouterOuvrageResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterOuvrageResponse")
    public void ajouterOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Ouvrage arg0
    );

    @WebMethod
    @RequestWrapper(localName = "supprimerAuteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerAuteur")
    @ResponseWrapper(localName = "supprimerAuteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerAuteurResponse")
    public void supprimerAuteur(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod(operationName = "ModifierOuvrage")
    @RequestWrapper(localName = "ModifierOuvrage", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierOuvrage")
    @ResponseWrapper(localName = "ModifierOuvrageResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierOuvrageResponse")
    public void modifierOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Ouvrage arg0
    );

    @WebMethod
    @RequestWrapper(localName = "supprimerGenre", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerGenre")
    @ResponseWrapper(localName = "supprimerGenreResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerGenreResponse")
    public void supprimerGenre(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod
    @RequestWrapper(localName = "ajouterAuteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterAuteur")
    @ResponseWrapper(localName = "ajouterAuteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterAuteurResponse")
    public void ajouterAuteur(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Auteur arg0
    );

    @WebMethod
    @RequestWrapper(localName = "supprimerExemplaire", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerExemplaire")
    @ResponseWrapper(localName = "supprimerExemplaireResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerExemplaireResponse")
    public void supprimerExemplaire(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod
    @RequestWrapper(localName = "rechercherparISBN", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherparISBN")
    @ResponseWrapper(localName = "rechercherparISBNResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherparISBNResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.biblio.p7.service.Ouvrage rechercherparISBN(
        @WebParam(name = "isbn", targetNamespace = "")
        java.lang.String isbn
    );

    @WebMethod
    @RequestWrapper(localName = "afficherEditeur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherEditeur")
    @ResponseWrapper(localName = "afficherEditeurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherEditeurResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Editeur> afficherEditeur();

    @WebMethod
    @RequestWrapper(localName = "ajouterExemplaire", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterExemplaire")
    @ResponseWrapper(localName = "ajouterExemplaireResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterExemplaireResponse")
    public void ajouterExemplaire(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Exemplaire arg0
    );

    @WebMethod
    @RequestWrapper(localName = "modifierAuteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierAuteur")
    @ResponseWrapper(localName = "modifierAuteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierAuteurResponse")
    public void modifierAuteur(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Auteur arg0
    );

    @WebMethod
    @RequestWrapper(localName = "ajouterVersion", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterVersion")
    @ResponseWrapper(localName = "ajouterVersionResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterVersionResponse")
    public void ajouterVersion(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.EditionOuvrage arg0
    );

    @WebMethod
    @RequestWrapper(localName = "modifierVersion", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierVersion")
    @ResponseWrapper(localName = "modifierVersionResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierVersionResponse")
    public void modifierVersion(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.EditionOuvrage arg0
    );

    @WebMethod
    @RequestWrapper(localName = "supprimerEditeur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerEditeur")
    @ResponseWrapper(localName = "supprimerEditeurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerEditeurResponse")
    public void supprimerEditeur(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod(operationName = "ListerlesOuvrageparGenre")
    @RequestWrapper(localName = "ListerlesOuvrageparGenre", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ListerlesOuvrageparGenre")
    @ResponseWrapper(localName = "ListerlesOuvrageparGenreResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ListerlesOuvrageparGenreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Ouvrage> listerlesOuvrageparGenre(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "afficherAuteur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherAuteur")
    @ResponseWrapper(localName = "afficherAuteurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherAuteurResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Auteur> afficherAuteur();

    @WebMethod
    @RequestWrapper(localName = "modifierExemplaire", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierExemplaire")
    @ResponseWrapper(localName = "modifierExemplaireResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierExemplaireResponse")
    public void modifierExemplaire(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Exemplaire arg0
    );

    @WebMethod
    @RequestWrapper(localName = "ajouterGenre", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterGenre")
    @ResponseWrapper(localName = "ajouterGenreResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterGenreResponse")
    public void ajouterGenre(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Genre arg0
    );

    @WebMethod
    @RequestWrapper(localName = "ajouterEditeur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterEditeur")
    @ResponseWrapper(localName = "ajouterEditeurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AjouterEditeurResponse")
    public void ajouterEditeur(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Editeur arg0
    );

    @WebMethod
    @RequestWrapper(localName = "afficherVersion", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherVersion")
    @ResponseWrapper(localName = "afficherVersionResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.EditionOuvrage> afficherVersion();

    @WebMethod
    @RequestWrapper(localName = "rechercherparOuvrage", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherparOuvrage")
    @ResponseWrapper(localName = "rechercherparOuvrageResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.RechercherparOuvrageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.biblio.p7.service.Ouvrage rechercherparOuvrage(
        @WebParam(name = "intituleOuvrage", targetNamespace = "")
        java.lang.String intituleOuvrage
    );

    @WebMethod
    @RequestWrapper(localName = "afficherExemplaire", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherExemplaire")
    @ResponseWrapper(localName = "afficherExemplaireResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherExemplaireResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Exemplaire> afficherExemplaire();

    @WebMethod
    @RequestWrapper(localName = "modifierEditeur", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierEditeur")
    @ResponseWrapper(localName = "modifierEditeurResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierEditeurResponse")
    public void modifierEditeur(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Editeur arg0
    );

    @WebMethod
    @RequestWrapper(localName = "modifierGenre", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierGenre")
    @ResponseWrapper(localName = "modifierGenreResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ModifierGenreResponse")
    public void modifierGenre(
        @WebParam(name = "arg0", targetNamespace = "")
        org.biblio.p7.service.Genre arg0
    );

    @WebMethod
    @RequestWrapper(localName = "afficherGenre", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherGenre")
    @ResponseWrapper(localName = "afficherGenreResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.AfficherGenreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Genre> afficherGenre();

    @WebMethod
    @RequestWrapper(localName = "supprimerOuvrage", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerOuvrage")
    @ResponseWrapper(localName = "supprimerOuvrageResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerOuvrageResponse")
    public void supprimerOuvrage(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );

    @WebMethod(operationName = "ListerlesOuvrages")
    @RequestWrapper(localName = "ListerlesOuvrages", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ListerlesOuvrages")
    @ResponseWrapper(localName = "ListerlesOuvragesResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.ListerlesOuvragesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.biblio.p7.service.Ouvrage> listerlesOuvrages();

    @WebMethod
    @RequestWrapper(localName = "supprimerVersion", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerVersion")
    @ResponseWrapper(localName = "supprimerVersionResponse", targetNamespace = "http://service.p7.biblio.org/", className = "org.biblio.p7.service.SupprimerVersionResponse")
    public void supprimerVersion(
        @WebParam(name = "iD", targetNamespace = "")
        java.lang.Integer iD
    );
}
