
package org.biblio.p7.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-03-19T22:10:30.400+01:00
 * Generated source version: 3.2.5
 *
 */
public final class OuvrageService_OuvrageServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.p7.biblio.org/", "OuvrageService");

    private OuvrageService_OuvrageServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OuvrageService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OuvrageService_Service ss = new OuvrageService_Service(wsdlURL, SERVICE_NAME);
        OuvrageService port = ss.getOuvrageServicePort();

        {
        System.out.println("Invoking ajouterOuvrage...");
        org.biblio.p7.service.Ouvrage _ajouterOuvrage_arg0 = null;
        port.ajouterOuvrage(_ajouterOuvrage_arg0);


        }
        {
        System.out.println("Invoking supprimerAuteur...");
        java.lang.Integer _supprimerAuteur_iD = null;
        port.supprimerAuteur(_supprimerAuteur_iD);


        }
        {
        System.out.println("Invoking modifierOuvrage...");
        org.biblio.p7.service.Ouvrage _modifierOuvrage_arg0 = null;
        port.modifierOuvrage(_modifierOuvrage_arg0);


        }
        {
        System.out.println("Invoking supprimerGenre...");
        java.lang.Integer _supprimerGenre_iD = null;
        port.supprimerGenre(_supprimerGenre_iD);


        }
        {
        System.out.println("Invoking ajouterAuteur...");
        org.biblio.p7.service.Auteur _ajouterAuteur_arg0 = null;
        port.ajouterAuteur(_ajouterAuteur_arg0);


        }
        {
        System.out.println("Invoking supprimerExemplaire...");
        java.lang.Integer _supprimerExemplaire_iD = null;
        port.supprimerExemplaire(_supprimerExemplaire_iD);


        }
        {
        System.out.println("Invoking rechercherparISBN...");
        java.lang.String _rechercherparISBN_isbn = "";
        org.biblio.p7.service.Ouvrage _rechercherparISBN__return = port.rechercherparISBN(_rechercherparISBN_isbn);
        System.out.println("rechercherparISBN.result=" + _rechercherparISBN__return);


        }
        {
        System.out.println("Invoking afficherEditeur...");
        java.util.List<org.biblio.p7.service.Editeur> _afficherEditeur__return = port.afficherEditeur();
        System.out.println("afficherEditeur.result=" + _afficherEditeur__return);


        }
        {
        System.out.println("Invoking ajouterExemplaire...");
        org.biblio.p7.service.Exemplaire _ajouterExemplaire_arg0 = null;
        port.ajouterExemplaire(_ajouterExemplaire_arg0);


        }
        {
        System.out.println("Invoking modifierAuteur...");
        org.biblio.p7.service.Auteur _modifierAuteur_arg0 = null;
        port.modifierAuteur(_modifierAuteur_arg0);


        }
        {
        System.out.println("Invoking ajouterVersion...");
        org.biblio.p7.service.EditionOuvrage _ajouterVersion_arg0 = null;
        port.ajouterVersion(_ajouterVersion_arg0);


        }
        {
        System.out.println("Invoking modifierVersion...");
        org.biblio.p7.service.EditionOuvrage _modifierVersion_arg0 = null;
        port.modifierVersion(_modifierVersion_arg0);


        }
        {
        System.out.println("Invoking supprimerEditeur...");
        java.lang.Integer _supprimerEditeur_iD = null;
        port.supprimerEditeur(_supprimerEditeur_iD);


        }
        {
        System.out.println("Invoking listerlesOuvrageparGenre...");
        java.lang.Integer _listerlesOuvrageparGenre_arg0 = null;
        java.util.List<org.biblio.p7.service.Ouvrage> _listerlesOuvrageparGenre__return = port.listerlesOuvrageparGenre(_listerlesOuvrageparGenre_arg0);
        System.out.println("listerlesOuvrageparGenre.result=" + _listerlesOuvrageparGenre__return);


        }
        {
        System.out.println("Invoking afficherAuteur...");
        java.util.List<org.biblio.p7.service.Auteur> _afficherAuteur__return = port.afficherAuteur();
        System.out.println("afficherAuteur.result=" + _afficherAuteur__return);


        }
        {
        System.out.println("Invoking modifierExemplaire...");
        org.biblio.p7.service.Exemplaire _modifierExemplaire_arg0 = null;
        port.modifierExemplaire(_modifierExemplaire_arg0);


        }
        {
        System.out.println("Invoking ajouterGenre...");
        org.biblio.p7.service.Genre _ajouterGenre_arg0 = null;
        port.ajouterGenre(_ajouterGenre_arg0);


        }
        {
        System.out.println("Invoking ajouterEditeur...");
        org.biblio.p7.service.Editeur _ajouterEditeur_arg0 = null;
        port.ajouterEditeur(_ajouterEditeur_arg0);


        }
        {
        System.out.println("Invoking afficherVersion...");
        java.util.List<org.biblio.p7.service.EditionOuvrage> _afficherVersion__return = port.afficherVersion();
        System.out.println("afficherVersion.result=" + _afficherVersion__return);


        }
        {
        System.out.println("Invoking rechercherparOuvrage...");
        java.lang.String _rechercherparOuvrage_intituleOuvrage = "";
        org.biblio.p7.service.Ouvrage _rechercherparOuvrage__return = port.rechercherparOuvrage(_rechercherparOuvrage_intituleOuvrage);
        System.out.println("rechercherparOuvrage.result=" + _rechercherparOuvrage__return);


        }
        {
        System.out.println("Invoking afficherExemplaire...");
        java.util.List<org.biblio.p7.service.Exemplaire> _afficherExemplaire__return = port.afficherExemplaire();
        System.out.println("afficherExemplaire.result=" + _afficherExemplaire__return);


        }
        {
        System.out.println("Invoking modifierEditeur...");
        org.biblio.p7.service.Editeur _modifierEditeur_arg0 = null;
        port.modifierEditeur(_modifierEditeur_arg0);


        }
        {
        System.out.println("Invoking modifierGenre...");
        org.biblio.p7.service.Genre _modifierGenre_arg0 = null;
        port.modifierGenre(_modifierGenre_arg0);


        }
        {
        System.out.println("Invoking afficherGenre...");
        java.util.List<org.biblio.p7.service.Genre> _afficherGenre__return = port.afficherGenre();
        System.out.println("afficherGenre.result=" + _afficherGenre__return);


        }
        {
        System.out.println("Invoking supprimerOuvrage...");
        java.lang.Integer _supprimerOuvrage_iD = null;
        port.supprimerOuvrage(_supprimerOuvrage_iD);


        }
        {
        System.out.println("Invoking listerlesOuvrages...");
        java.util.List<org.biblio.p7.service.Ouvrage> _listerlesOuvrages__return = port.listerlesOuvrages();
        System.out.println("listerlesOuvrages.result=" + _listerlesOuvrages__return);


        }
        {
        System.out.println("Invoking supprimerVersion...");
        java.lang.Integer _supprimerVersion_iD = null;
        port.supprimerVersion(_supprimerVersion_iD);


        }

        System.exit(0);
    }

}
